config/routes.rb
Rails.application.routes.draw do

  resources :articles
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end


  def edit
    @article = Article.find(params[:id])
    
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  

  def show
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :description, :price)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |form| %>

<p>
    <%= form.label :title %>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :description %>
    <%= form.text_field :description %>
</p>

<p>
    <%= form.label :price %>
    <%= form.text_field :price %>
</p>

<p>
    <%= form.submit%>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1><br/>

<%= render 'form' %>

<%= link_to 'Back to home', articles_path%>

app/views/articles/index.html.erb
<h1> Listing all the articles</h1><br/>

Create a new article by clicking on this <%= link_to 'link', new_article_path %> <br/>

<table>
    <tr>
        <th> Title </th>
        <th> Description </th>
        <th> Price </th>
        <th> </th>
    </tr>

    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description%></td>
        <td><%= article.price%></td>
        <td><%= link_to 'Show', article_path(article)%></td>
        <td><%= link_to 'Edit', edit_article_path(article)%></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Do you want to delete the data?'}%></td>
    </tr>
</table>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1><br/>

<%= render 'form' %>

<%= link_to 'Back to home', articles_path%>

app/views/articles/show.html.erb
<h2>Showing the selected article and the article is <%= @article.title%></h2>
<p>
<strong>Title :</strong>
<%= @article.title %>
</p>

<p>
<strong>Description :</strong>
<%= @article.description %>
</p>

<p>
<strong>Price :</strong>
<%= @article.price %>
</p>

<%= link_to 'Back to home screen', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to my Blog</h1>
<p>Please click on my <%=link_to 'blog', articles_path%> to view the details</p>